### ISSUE TITLE
Using IsNullOrUndefined for validations

### ISSUE THREAD

**Issue by Lowpoc** [logiqsystem/inoutjs#8]
The class FileWriter Wrapper repeat the validation ``if (content == null || content == undefined )```, for best a maintenance  we can using the method **isNullOrUndefined**

![usingisnullorundefined](https://user-images.githubusercontent.com/17841549/50097713-3b024600-01f9-11e9-9399-eb7af2395422.png)

**Comment by marxjmoura** [comment]
Hi @Lowpoc. Thank you for sharing. I will improve the library not only internally but also adding new features as soon as I can.

**Comment by Lowpoc** [comment]
Nice man,  very good your lib.

**Comment by marxjmoura** [comment]
I'm going to close this issue. I will keep you informed about any updates.
